name: check footnotes

on:
  push:

jobs:
  check-footnotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guarantee correct numbering of notes and inline citations
        run: |
          python3 scripts/fix_note_nums.py --no-fix --except reorg-ideas.md --except aold.md *.md
